# Generated by Django 4.0.1 on 2022-01-31 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Univer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univer_name', models.CharField(max_length=200, verbose_name='нименование университета')),
                ('kol_vo_sotrud', models.IntegerField(verbose_name='кол-во сотрудников')),
                ('kol_vo_kafedr', models.IntegerField(verbose_name='кол-во кафедр')),
            ],
        ),
        migrations.CreateModel(
            name='Sotrud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_sotrud', models.TextField(verbose_name='ФИО сотрудника')),
                ('univer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.univer')),
            ],
        ),
    ]
