# Generated by Django 4.0.1 on 2022-02-03 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakultet_name', models.CharField(max_length=200, verbose_name='Наименование факультета')),
            ],
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kafedra_name', models.CharField(max_length=200, verbose_name='Наименование кафедры')),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.fakultet')),
            ],
        ),
        migrations.CreateModel(
            name='Univer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univer_name', models.CharField(max_length=200, verbose_name='Наименование университета')),
                ('orgsid_univer', models.BigIntegerField(verbose_name='OrgsID на elibrary.ru ')),
            ],
        ),
        migrations.CreateModel(
            name='Sotrud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_sotrud', models.TextField(verbose_name='ФИО сотрудника')),
                ('authorid_sotrud', models.BigIntegerField(verbose_name='AuthorID на elibrary.ru')),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.kafedra')),
            ],
        ),
        migrations.AddField(
            model_name='fakultet',
            name='univer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.univer'),
        ),
    ]
