# Generated by Django 4.0.2 on 2022-05-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakultet_sname', models.CharField(max_length=100, verbose_name='Сокращенное наименование факультета')),
                ('fakultet_name', models.CharField(max_length=200, verbose_name='Наименование факультета')),
            ],
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kafedra_sname', models.CharField(max_length=200, verbose_name='Сокращенное наименование кафедры')),
                ('kafedra_name', models.CharField(max_length=200, verbose_name='Наименование кафедры')),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.fakultet')),
            ],
        ),
        migrations.CreateModel(
            name='Sotrud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_s', models.CharField(max_length=200, verbose_name='Фамилия И О')),
                ('fio', models.TextField(verbose_name='Фамилия Имя Отчество')),
                ('authorid_sotrud', models.BigIntegerField(verbose_name='AuthorID на elibrary.ru')),
                ('elib_publ_rinc', models.IntegerField(verbose_name='Публикаций в РИНЦ (elibrary)')),
                ('elib_publ_yrinc', models.IntegerField(verbose_name='Публикации входящие в ядро РИНЦ (elibrary)')),
                ('elib_cit_rinc', models.IntegerField(verbose_name='Цитирования публикаций в РИНЦ (elibrary)')),
                ('elib_hir_rinc', models.IntegerField(verbose_name='Индекс Хирша по публикациям в РИНЦ (elibrary)')),
                ('otch_publ_rinc', models.IntegerField(verbose_name='Публикаций в РИНЦ (отчетные)')),
                ('otch_publ_yrinc', models.IntegerField(verbose_name='Публикации входящие в ядро РИНЦ (отчетные)')),
                ('otch_cit_rinc', models.IntegerField(verbose_name='Цитирования публикаций в РИНЦ (отчетные)')),
                ('otch_hir_rinc', models.IntegerField(verbose_name='Индекс Хирша по публикациям в РИНЦ (отчетные)')),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.kafedra')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100, verbose_name='Год')),
                ('elib_publ_rinc', models.IntegerField(verbose_name='Публикаций в РИНЦ (elibrary)')),
                ('elib_publ_yrinc', models.IntegerField(verbose_name='Публикации входящие в ядро РИНЦ (elibrary)')),
                ('elib_cit_rinc', models.IntegerField(verbose_name='Цитирования публикаций в РИНЦ (elibrary)')),
                ('otch_publ_rinc', models.IntegerField(verbose_name='Публикаций в РИНЦ (отчетные)')),
                ('otch_publ_yrinc', models.IntegerField(verbose_name='Публикации входящие в ядро РИНЦ (отчетные)')),
                ('otch_cit_rinc', models.IntegerField(verbose_name='Цитирования публикаций в РИНЦ (отчетные)')),
                ('sotrud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.sotrud')),
            ],
        ),
    ]
